# List of European countries to compare with France
countries:
  - "BE"
  - "DE"
  - "IT"
  - "ES"

# Posting configuration
post_interval_hours: 6

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'bot.log'

emojis:
  thresholds:
    very_low: 100
    low: 200
    medium: 400
  symbols:
    very_low: "ğŸŸ¢"
    low: "ğŸŸ¡"
    medium: "ğŸŸ "
    high: "ğŸ”´"
  power_sources:
    nuclear: "âš›ï¸"
    hydro: "ğŸŒŠ"
    gas: "ğŸ”¥"
    wind: "ğŸ’¨"
    coal: "ğŸª¨"
    oil: "ğŸ›¢ï¸"
    solar: "â˜€ï¸"
    biomass: "ğŸ”¥"
    geothermal: "ğŸŒ‹"
    battery_storage: "ğŸ”‹"
    hydro_storage: "ğŸŒŠ"

account_tag: "@electricitymaps.bsky.social"