# Configure the base country that will appear in all posts
base_country: "FR"

# List of European countries to compare with France
countries:
  - DE
  - BE
  - ES
  - IT
  - GB
  - NL
  - PL
  - PT

country_names:
  FR: "France"
  DE: "Germany"
  BE: "Belgium"
  ES: "Spain"
  IT: "Italy"
  GB: "Britain"
  NL: "Netherlands"
  PL: "Poland"
  PT: "Portugal"

# Posting configuration
post_interval_hours: 6

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'bot.log'

emojis:
  thresholds:
    very_low: 100
    low: 200
    medium: 400
  symbols:
    very_low: "ğŸŸ¢"
    low: "ğŸŸ¡"
    medium: "ğŸŸ "
    high: "ğŸ”´"
  power_sources:
    nuclear: "âš›ï¸"
    hydro: "ğŸŒŠ"
    gas: "ğŸ”¥"
    wind: "ğŸ’¨"
    coal: "ğŸª¨"
    oil: "ğŸ›¢ï¸"
    solar: "â˜€ï¸"
    biomass: "ğŸ”¥"
    geothermal: "ğŸŒ‹"
    battery_storage: "ğŸ”‹"
    hydro_storage: "ğŸŒŠ"

account_tag: "@electricitymaps.bsky.social"